baseurl = "https://blog.refrain.cc"
languageCode = "en-us"
title = "夜行列车"
theme = "hugo-tania"
paginate = 6

# disqusShortname = "https-blog-refrain-cc-app"

[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = "😎"

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true

  siteName = "Refrain"
  siteDesc = "A misty moom..."
  author = "Refrain"
  toc = true
  [params.colorScheme]
    # Enable toggle colorScheme
    # Default to true
    toggle = true
    # Default colorScheme
    # Default to auto
  #  default = auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = ""
    facebook = ""
    github = ""
    instagram = ""
    linkedin = ""
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    twitter = ""
    twitch = ""
    whatsapp = ""
  
  # Comments settigns
  [params.comments]
    # enabled = true
    enabled = false
    provider = "disqus"

[menu]
[[menu.header]]
  name = "Articles"
  url = "/articles/"
[[menu.footer]]
    name = "RSS"
    url = "/index.xml"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]